### ISSUE TITLE
Edit permission is required to create a file

### ISSUE THREAD

**Issue by sebj54** [directus/api#1417]
# Bug Report

## Steps to Reproduce

1. Create a user role with "add" and "view" permissions for `directus_files` table
2. Create a user and choose this new role
3. Log in as this user
4. Go to File Library
5. Create a file (upload)

## Expected Behavior

File should be uploaded and created successfully.

## Actual Behavior

An error is shown:

> You are not allowed to upload, edit or delete files

## Other Context & Screenshots

Here is an error log :

```
[2019-11-12 10:02:28] api[_].ERROR: Directus\Exception\ForbiddenException: You are not allowed to upload, edit or delete files in C:\wamp64\www\gamax-api\src\core\Directus\Application\CoreServicesProvider.php:706
Stack trace:
#0 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#1 C:\wamp64\www\gamax-api\src\core\Directus\Hook\Emitter.php(291): call_user_func_array
#2 C:\wamp64\www\gamax-api\src\core\Directus\Hook\Emitter.php(119): Directus\Hook\Emitter->executeListeners
#3 C:\wamp64\www\gamax-api\src\core\Directus\Filesystem\Files.php(295): Directus\Hook\Emitter->run
#4 C:\wamp64\www\gamax-api\src\core\Directus\Application\CoreServicesProvider.php(332): Directus\Filesystem\Files->saveData
#5 C:\wamp64\www\gamax-api\src\core\Directus\Application\CoreServicesProvider.php(376): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#6 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#7 C:\wamp64\www\gamax-api\src\core\Directus\Hook\Emitter.php(291): call_user_func_array
#8 C:\wamp64\www\gamax-api\src\core\Directus\Hook\Emitter.php(151): Directus\Hook\Emitter->executeListeners
#9 C:\wamp64\www\gamax-api\src\core\Directus\Database\TableGateway\BaseTableGateway.php(1594): Directus\Hook\Emitter->apply
#10 C:\wamp64\www\gamax-api\src\core\Directus\Database\TableGateway\BaseTableGateway.php(787): Directus\Database\TableGateway\BaseTableGateway->applyHook
#11 C:\wamp64\www\gamax-api\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert
#12 C:\wamp64\www\gamax-api\src\core\Directus\Database\TableGateway\BaseTableGateway.php(390): Zend\Db\TableGateway\AbstractTableGateway->insert
#13 C:\wamp64\www\gamax-api\src\core\Directus\Database\TableGateway\RelationalTableGateway.php(412): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray
#14 C:\wamp64\www\gamax-api\src\core\Directus\Services\FilesServices.php(59): Directus\Database\TableGateway\RelationalTableGateway->createRecord
#15 C:\wamp64\www\gamax-api\src\endpoints\Files.php(84): Directus\Services\FilesServices->create
#16 [internal function]: Directus\Api\Routes\Files->create
#17 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(40): call_user_func
#18 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#19 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#20 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#21 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#24 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\AuthenticationMiddleware.php(121): Slim\Route->Slim\{closure}
#25 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#26 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#29 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#30 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#31 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#34 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#35 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\Route.php(268): Slim\Route->callMiddlewareStack
#36 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\App.php(503): Slim\Route->run
#37 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#38 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#39 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#42 C:\wamp64\www\gamax-api\vendor\directus\proxy-detection\src\ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#43 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#44 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#45 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#46 [internal function]: Slim\DeferredCallable->__invoke
#47 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#48 C:\wamp64\www\gamax-api\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#49 [internal function]: RKA\Middleware\IpAddress->__invoke
#50 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#51 [internal function]: Slim\DeferredCallable->__invoke
#52 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#53 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(66): Slim\App->Slim\{closure}
#54 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#55 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#56 [internal function]: Slim\DeferredCallable->__invoke
#57 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#58 C:\wamp64\www\gamax-api\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
#59 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#60 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#61 [internal function]: Slim\DeferredCallable->__invoke
#62 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#63 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#64 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\App.php(392): Slim\App->callMiddlewareStack
#65 C:\wamp64\www\gamax-api\vendor\slim\slim\Slim\App.php(297): Slim\App->process
#66 C:\wamp64\www\gamax-api\src\core\Directus\Application\Application.php(161): Slim\App->run
#67 C:\wamp64\www\gamax-api\public\index.php(5): Directus\Application\Application->run [] []
```

I actually fixed the issue by changing a single function call, on this file https://github.com/directus/api/blob/0491f6af049f0a18d670f034916f2ec39c2c034b/src/core/Directus/Application/CoreServicesProvider.php#L705. `canUpdate` should be `canCreate`.

I considered making a PR for this but I don't know what side effect this change could have so here is an issue instead!

## Technical Details

- Device: Laptop
- OS: latest Windows 10
- Web Server: [eg: Apache 2.4.37]
- PHP Version: 7.3.1
- Database: MySQL 5.7.24
- Install Method: cloned master branch

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1452
