### ISSUE TITLE
Creating users via API returns "401 Unauthorized" (v8)

### ISSUE THREAD

**Issue by anelad** [directus/api#1465]
# Bug Report

Creating users from API returns "401: Unauthorized Request".

First, I need to say that updating an existing user works - of course with including token. So there is no "wrong url" or something else.

## Steps to Reproduce

I give required permission on the role **public** to create users:

![Screen Shot 2019-11-23 at 17 21 15](https://user-images.githubusercontent.com/5767654/69480135-ae530580-0e15-11ea-9b7f-08b54108de16.png)

here is my code (Angular):
``` typescript
  public async createUser(firstName: string, lastName: string, email: string, password: string): Promise<any> {
    const data = { first_name: firstName, last_name: lastName, email: email, password: password, status: "active", roles: [3], timezone: "Europe/Vienna", locale: "tr-TR" }
    const json = JSON.stringify(data);
    const headers = new HttpHeaders({
      "Content-Type": "application/json",
    });
    return this.http.post('https://api.myapp.com/project-id/users', json, { headers });
  }
```

Error from browser console: 
```
[Log] creating user failed (main.js, line 947)
HttpErrorResponse

error: {error: {code: 3, message: "Unauthorized request"}}

headers: HttpHeaders {normalizedNames: Map, lazyUpdate: null, lazyInit: function}

message: "Http failure response for https://cms.uflymarket.com/ufly-market/users: 401 OK"

name: "HttpErrorResponse"

ok: false

status: 401

statusText: "OK"

url: "https://cms.uflymarket.com/ufly-market/users"

HttpErrorResponse Prototype
```

Error from log file:

```
[2019-11-23 09:05:14] api[ufly-market].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Permissions/Acl.php:991
Stack trace:
#0 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1178): Directus\Permissions\Acl->enforceReadOnce
#1 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1161): Directus\Database\TableGateway\BaseTableGateway->enforceReadPermission
#2 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1283): Directus\Database\TableGateway\RelationalTableGateway->fetchItems
#3 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(879): Directus\Database\TableGateway\RelationalTableGateway->fetchData
#4 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Services/ItemsService.php(561): Directus\Database\TableGateway\RelationalTableGateway->getItems
#5 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Services/ItemsService.php(47): Directus\Services\ItemsService->isManyToManyField
#6 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Services/UsersService.php(58): Directus\Services\ItemsService->createItem
#7 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/endpoints/Users.php(75): Directus\Services\UsersService->create
#8 [internal function]: Directus\Api\Routes\Users->create
#9 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#10 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#11 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#12 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#13 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#14 [internal function]: Slim\DeferredCallable->__invoke
#15 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#16 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(121): Slim\Route->Slim\{closure}
#17 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#18 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#19 [internal function]: Slim\DeferredCallable->__invoke
#20 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#21 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#22 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#23 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#24 [internal function]: Slim\DeferredCallable->__invoke
#25 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#26 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#27 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#28 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#29 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#30 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#31 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#34 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#35 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#36 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#37 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#38 [internal function]: Slim\DeferredCallable->__invoke
#39 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#40 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#41 [internal function]: RKA\Middleware\IpAddress->__invoke
#42 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#43 [internal function]: Slim\DeferredCallable->__invoke
#44 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#45 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\App->Slim\{closure}
#46 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#47 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#48 [internal function]: Slim\DeferredCallable->__invoke
#49 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#50 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#51 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#52 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#53 [internal function]: Slim\DeferredCallable->__invoke
#54 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#55 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#56 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#57 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#58 [internal function]: Slim\DeferredCallable->__invoke
#59 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#60 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#61 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#62 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#63 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Application.php(161): Slim\App->run
#64 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/public/index.php(5): Directus\Application\Application->run [] []
```

Also according to the docs, only _email_ and _password_ should be enough to create a user. But API says it requires _status_, _timezone_, _roles_. If I do not include them in payload, it complains about that.

**Comment by anelad** [comment]
![Screen-Recording-2019-11-24-at-18 03 19](https://user-images.githubusercontent.com/5767654/69496738-4ddfc900-0ee6-11ea-891a-bcfc5f05b824.gif)

**Comment by bjgajjar** [comment]
@anelad - May I know your version? This is not reproducible in the latest version.

**Comment by anelad** [comment]
rc2 fixes. I was created a script to check new versions everyday, but somehow it did not pull the rc2.
