### ISSUE TITLE
V8 - api[].ERROR: ParseError: syntax error, unexpected ':' in /var/www/migrations/install/20180220023217_create_roles_table.php:173

### ISSUE THREAD

**Issue by everyx** [directus/api#1488]
# Bug Report

## Steps to Reproduce

1. Go to `http://project.com/admin` from new fresh install
2. Follow step to create project and at the "database connection" step, we get server error.

## Technical Details

- Device: Desktop
- OS: Docker Desktop on Windows 10
- Web Server: Caddy on Docker
- PHP Version: 7.3
- Database: MySQL 8
- Install Method: cloned `develop` branch

Api log below
```log
[2019-11-27 08:24:39] api[].ERROR: ParseError: syntax error, unexpected ':' in /var/www/migrations/install/20180220023217_create_roles_table.php:173
Stack trace:
#0 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(305): Phinx\Migration\Manager->getMigrations
#1 /var/www/src/core/Directus/Util/Installation/InstallerUtils.php(237): Phinx\Migration\Manager->migrate
#2 /var/www/src/core/Directus/Util/Installation/InstallerUtils.php(204): Directus\Util\Installation\InstallerUtils::runMigrationAndSeeder
#3 /var/www/src/core/Directus/Services/ProjectService.php(109): Directus\Util\Installation\InstallerUtils::createTables
#4 /var/www/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
#5 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
#6 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#7 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#8 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
#9 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#10 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#11 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#12 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#13 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#14 [internal function]: Slim\DeferredCallable->__invoke
#15 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#16 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#17 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#18 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#19 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#20 /var/www/public/index.php(5): Directus\Application\Application->run [] []
[2019-11-27 08:24:41] api[].ERROR: Directus\Exception\UnauthorizedException: Permission denied: Superadmin Only in /var/www/src/core/Directus/Services/ProjectService.php:74
Stack trace:
#0 /var/www/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
#1 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
#2 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#3 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#4 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
#5 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#6 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#7 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#8 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#9 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#10 [internal function]: Slim\DeferredCallable->__invoke
#11 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#12 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#13 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#14 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#15 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#16 /var/www/public/index.php(5): Directus\Application\Application->run [] []
[2019-11-27 08:24:46] api[].ERROR: Directus\Exception\UnauthorizedException: Permission denied: Superadmin Only in /var/www/src/core/Directus/Services/ServerService.php:80
Stack trace:
#0 /var/www/src/endpoints/Server.php(69): Directus\Services\ServerService->validateServerInfo
#1 [internal function]: Directus\Api\Routes\Server->getInfo
#2 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#3 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#4 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
#5 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#6 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#7 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#8 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#9 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#10 [internal function]: Slim\DeferredCallable->__invoke
#11 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#12 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#13 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#14 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#15 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#16 /var/www/public/index.php(5): Directus\Application\Application->run [] []
[2019-11-27 03:24:50] api[fengsi].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (42S02 - 1146 - Table 'test.directus_settings' doesn't exist) in /var/www/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
Stack trace:
#0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute
#1 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Zend\Db\TableGateway\AbstractTableGateway->executeSelect
#2 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(196): Zend\Db\TableGateway\AbstractTableGateway->selectWith
#3 /var/www/src/core/Directus/Application/CoreServicesProvider.php(1176): Zend\Db\TableGateway\AbstractTableGateway->select
#4 /var/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#5 /var/www/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet
#6 /var/www/src/helpers/settings.php(20): Directus\Container\Container->get
#7 /var/www/src/helpers/settings.php(35): Directus\get_directus_settings
#8 /var/www/src/helpers/settings.php(145): Directus\get_directus_setting
#9 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(16): Directus\get_trusted_proxies
#10 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#11 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#15 [internal function]: RKA\Middleware\IpAddress->__invoke
#16 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#21 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#24 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#25 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#26 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#30 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#31 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#32 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#33 /var/www/public/index.php(5): Directus\Application\Application->run [] []
```

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1489
