### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by sydney-d** [directus/api#1647]
# Bug Report

## Steps to Reproduce
Upgrade to V8, via FTP, V7 was working fine.
Clear session cookies
Enter email and password

## Expected Behavior
Access to admin dashboard

## Actual Behavior
Error screen : 
`Server Error`
`Something is wrong with this project’s server or database.`

_Note_: If I don't remove cookies and clear cache I have a similar issue as the one described here : 
https://github.com/directus/directus/issues/2510

## Other Context & Screenshots
**Error sceen**
![image](https://user-images.githubusercontent.com/46789893/72263451-2c16de80-3619-11ea-8f2f-bc12474f4beb.png)

**API calls**
![image](https://user-images.githubusercontent.com/46789893/72263424-215c4980-3619-11ea-86f4-d9b24cb3961c.png)

`public/_/auth/authenticate`
 is returning : 
`{"data":{"user":{"id":"1", ... }},"public":true}`

`public/_/users/me?fields[0]=id&fields[1]=avatar.*&fields[2]=email&fields[3]=first_name&fields[4]=last_name&fields[5]=locale&fields[6]=role.*&fields[7]=last_page&fields[8]=theme` 
is returning : 
`{"data":{"id":1,", ... },"theme":"auto"}}`

`/public/layouts`
 is returning : 
`{"error":{"code":108,"message":"User not authenticated"}}`

`/public/collections` and `public/_/relations?limit=-1` 
are returning : 
`{"error":{"code":3,"message":"Unauthorized request"}}`

`public/_/users/me?fields=*.*` 
is returning : 
`{"error":{"code":203,"message":"Item not found"}}`

## Technical Details

- Device: Firefox and chrome desktop
- OS: windows 7
- Web Server: Apache
- PHP Version: 7.3
- Database: 
- Directus Release Version: v8.3.1
- Install Method: FTP upload

Thank you for your help.

**Comment by sydney-d** [comment]
I've successfully made the upgrade on my local environment, here is a comparaison between the two environments : 

-----
### GET `_/` : 

#### Working env response : 
```
api: 
	version: "8.3.1"
	requires2FA: false
	database: "mysql"
	project_logo: null
	project_name: "Directus"
	project_color: "#13181a"
	project_foreground: null
	project_background: null
	default_locale: "en-US"
	telemetry: true
	project_public_note: null
server:
	max_upload_size: 2097152
	general: 
		php_version: "7.2.14"
		php_api: "apache2handler"
```
#### Failing env response: 
```
api:
	requires2FA: false
	project_logo: null
	project_color: "blue-grey-900"
	project_foreground: null
	project_background: null
	default_locale: "en-US"
	telemetry: true
	project_name: "Directus"
	project_public_note: null
public: true
```

#### differences : 
- `api.version` & `api.database` & `server: {...}`  are missing from failing env
- `public: true` is missing from working env

#### notes : 
This seems to be related to this block of code : https://github.com/directus/api/blob/79f4e032721d7c0b5002d8575bd50944ac1b9ac5/src/endpoints/ProjectHome.php#L19-L27
And we can conclude that at this point `$acl->getUserId()` returns a falsy value.

Same behaviour has been described here too : 
https://github.com/directus/directus/issues/2510#issuecomment-574122524

-----

### Cookies : 
#### Working env cookies : 
![image](https://user-images.githubusercontent.com/46789893/72353301-1fab8800-36e4-11ea-897e-632a07d2f9b3.png)

#### Failing env cookies : 
![image](https://user-images.githubusercontent.com/46789893/72353313-2a661d00-36e4-11ea-8c63-d3de534dad8d.png)

#### differences : 
- `directus-_-session` is missing from failing env.

-----

### Session storage : 
#### Working env session storage : 
![image](https://user-images.githubusercontent.com/46789893/72353469-6ac59b00-36e4-11ea-93e5-e9e95e464a97.png)


#### Failing env session storage : 
![image](https://user-images.githubusercontent.com/46789893/72353513-7b761100-36e4-11ea-9930-40a1f0d24566.png)

#### differences : 
- `directus-sdk-js` is missing from failing env.


#### differences : 
- `directus-_-session` is absent from failing env.

**Comment by sydney-d** [comment]
I just tried installing directus 8.3 on a clean azure PHP7.3 server instance (App Services).
Installation works perfectly, but then i'm unable to log in :
Error : **Couldn't reach API**

**Comment by bjgajjar** [comment]
>Error : Couldn't reach API

May I have a log of it?

**Comment by sydney-d** [comment]
@bjgajjar sure !

I've also sent you an email with credentials and an url, so you can reproduce the bug

```
// Multiple clicks on "Sign In" without reloading
// each time it displays a loader then "Couldn't reach API" :

[2020-01-16 18:37:02] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:37:13] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:04] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:07] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:09] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:12] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:15] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:16] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:18] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:19] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:20] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:22] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:23] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:23] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:24] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:26] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:27] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:39:29] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:40:32] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:40:33] api[directus8].ERROR: Failed generating the SQL query. [] []
[2020-01-16 18:40:35] api[directus8].ERROR: Failed generating the SQL query. [] []

// Finally (and randomly) something happens:
// Spinner is displayed, then I'm redirected to the page "Server Error Something is wrong with this project’s server or database." :

[2020-01-16 18:40:35] api[directus8].ERROR: Directus\Database\Exception\ItemNotFoundException: Item not found in /home/site/wwwroot/src/core/Directus/Services/ItemsService.php:138
Stack trace:
#0 /home/site/wwwroot/src/core/Directus/Services/UsersService.php(144): Directus\Services\ItemsService->findByIds
#1 /home/site/wwwroot/src/endpoints/Users.php(92): Directus\Services\UsersService->findByIds
#2 [internal function]: Directus\Api\Routes\Users->read
#3 /home/site/wwwroot/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#4 /home/site/wwwroot/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#7 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#8 [internal function]: Slim\DeferredCallable->__invoke
#9 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#10 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#11 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#12 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#16 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#17 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#21 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#22 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#25 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#26 /home/site/wwwroot/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#27 /home/site/wwwroot/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#28 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#29 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#30 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#31 [internal function]: Slim\DeferredCallable->__invoke
#32 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#33 /home/site/wwwroot/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#34 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#35 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#36 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /home/site/wwwroot/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#40 [internal function]: RKA\Middleware\IpAddress->__invoke
#41 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#45 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#46 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#49 /home/site/wwwroot/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#50 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#51 /home/site/wwwroot/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#52 [internal function]: Slim\DeferredCallable->__invoke
#53 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#54 /home/site/wwwroot/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#55 /home/site/wwwroot/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#56 /home/site/wwwroot/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#57 /home/site/wwwroot/src/core/Directus/Application/Application.php(161): Slim\App->run
#58 /home/site/wwwroot/public/index.php(5): Directus\Application\Application->run [] []

```

**Comment by sydney-d** [comment]
Fixed with https://github.com/directus/api/pull/1669
