### ISSUE TITLE
Directus 7 to 8 upgrade: can't login if auto_sign_out was set to null

### ISSUE THREAD

**Issue by ale-rinaldi** [directus/api#1702]
I had a Directus 7 instance where the value of the auto_sign_out setting was set to `null`, which was a working value.

After migrating to Directus 8, the login began to fail with the following error:
```
api[_].ERROR: Exception: DateTimeImmutable::__construct(): Failed to parse time string (now + minutes) at position 4 (+): Unexpected character in /var/directus/src/endpoints/Auth.php:120
Stack trace:
#0 /var/directus/src/endpoints/Auth.php(120): DateTimeImmutable->__construct
#1 /var/directus/src/endpoints/Auth.php(73): Directus\Api\Routes\Auth->storeCookieSession
#2 [internal function]: Directus\Api\Routes\Auth->authenticate
#3 /var/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#4 /var/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 /var/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#7 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#8 [internal function]: Slim\DeferredCallable->__invoke
#9 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#10 /var/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#11 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#12 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#16 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#17 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#18 /var/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#19 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#20 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /var/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#24 /var/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#25 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#26 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 /var/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#30 [internal function]: RKA\Middleware\IpAddress->__invoke
#31 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#34 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#35 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#36 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /var/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#40 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#41 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#45 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#46 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#47 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
```

I needed to manually access database and set a value for auto_sign_out (i.e. 10080, like in a fresh install) to make it working.

**Comment by bjgajjar** [comment]
@rijkvanzanten - If the user sets `auto_sign_out` as `null` then what will be the value of cookie expiration time? Currently, it based on `auto_sign_out` value.

**Comment by ale-rinaldi** [comment]
Hello,
I think this is the root cause of the issue, because in src/endpoints/Auth.php, lines 119-120, there is:

```php
$expirationMinutes =  get_directus_setting('auto_sign_out');
$expiry = new \DateTimeImmutable('now + '.$expirationMinutes.'minutes');
```

Since auto_sign_out is null, the composed string passed to DateTimeImmutable costructor is `now + minutes`, which is invalid and triggers the error.

**Comment by bjgajjar** [comment]
Thanks for the help @ale-rinaldi. I agree with that but this code exists for setting the cookie expiration time. And for that system is using `auto_sign_out`.

Thus, if the user sets it null then either we have to make it not nullable or we should add some default value.

That's why I'm asking the suggestion for the default value of cookie expiration time.

**Comment by rijkvanzanten** [comment]
We should use the default value if the value is `null`

**Comment by bjgajjar** [comment]
That's what I'm asking. `auto_sign_out` itself a default value. So we should decide the default value for this.

**Comment by rijkvanzanten** [comment]
New thought: if the users explicitly sets the auto sign out value to `null`, the cookie should never expire.

**Comment by ale-rinaldi** [comment]
> New thought: if the users explicitly sets the auto sign out value to `null`, the cookie should never expire.

How was it handled in Directus 7? Because as far as I remember, I never set that `null` value explicitly, so maybe `null` was the default value in Directus 7. If this is the case, that would mean that in all Directus 8 setups that are migrated from Directus 7, the cookie would never expire by default...

**Comment by hemratna** [comment]
@rijkvanzanten 
If auto sign out value is `null`, we will set the cookie that should never expire.
Please acknowledge.

**Comment by rijkvanzanten** [comment]
Acknowledged @hemratna.
