### ISSUE TITLE
upload video files to files endpoint :project/files

### ISSUE THREAD

**Issue by stevezaxz** [directus/api#1777]
Hi there!

Thanks for taking the time to notify the community of an issue or sharing your thoughts for a new feature.

Please be as detailed as possible so others know exactly what you're talking about.

For bugs, please include:
• Version of Directus - 8.5.5
• Error message (if any) - File not found at path: 
• Steps to reproduce
upload video files to files endpoint :project/files
and it will response with this error {"error":{"code":null,"message":"File not found at path: 161db893-0661-437d-9f42-9887c6010a99"}}
• PHP version 7.4
• MySQL version 5.7.29
• Webserver + version apache 2.4.14

Thanks!

**Comment by hemratna** [comment]
@stevezaxz Are you able to upload any other file type like image, pdf, etc.
I tried at my end (upload via APP) video uploading works fine. 
If you are not able to upload a video only, Can you please provide a video/screenshots?

**Comment by domdus** [comment]
Hi guys,

I got stuck at same issue with uploading other files than images, using the API (:project/files) endpoint.
Directus version is: 8.8.0

Images work fine - POST body example :
`{
	"data": "https://<domain>/test.jpg"
}`

Doing so with mp4, txt, pdf files does not work - Response body example:
`{
    "error": {
        "code": null,
        "message": "File not found at path: 5d9c07dc-b9d0-49e3-9da5-207525c4734d"
    }
}`

! All file types work when uploading via APP.

Logs:
`[2020-07-07 11:17:51] api[api].ERROR: League\Flysystem\FileNotFoundException: File not found at path: 5d9c07dc-b9d0-49e3-9da5-207525c4734d in /var/www/html/api8.server/vendor/league/flysystem/src/Filesystem.php:389
Stack trace:
#0 /var/www/html/api8.server/vendor/league/flysystem/src/Filesystem.php(283): League\Flysystem\Filesystem->assertPresent
#1 /var/www/html/api8.server/src/core/Directus/Filesystem/Files.php(455): League\Flysystem\Filesystem->getMimetype
#2 /var/www/html/api8.server/src/core/Directus/Filesystem/Files.php(409): Directus\Filesystem\Files->getFileInfoFromPath
#3 /var/www/html/api8.server/src/core/Directus/Filesystem/Files.php(306): Directus\Filesystem\Files->getFileInfo
#4 /var/www/html/api8.server/src/core/Directus/Services/FilesServices.php(94): Directus\Filesystem\Files->saveData
#5 /var/www/html/api8.server/src/core/Directus/Services/FilesServices.php(60): Directus\Services\FilesServices->getSaveData
#6 /var/www/html/api8.server/src/endpoints/Files.php(74): Directus\Services\FilesServices->create
#7 [internal function]: Directus\Api\Routes\Files->create`
{...}

Hope you can reproduce and fix it, Thanks!
