### ISSUE TITLE
M2M: can't select existing values

### ISSUE THREAD

**Issue by buenyamin-olgun** [directus/api#1791]
Version of Directus: 8.5.5

Problem:
- I've created previously a Many-to-many relationship which was working fine.

Here are the tables:
![image](https://user-images.githubusercontent.com/32687653/75548569-e5950c00-5a2d-11ea-9d19-e60438387b5a.png)

Suddenly it stopped working. I can use the many-to-many relationship by adding a new item to the table. But selecting an existing one is not possible:

![image](https://user-images.githubusercontent.com/32687653/75548733-44f31c00-5a2e-11ea-8334-1d883856936d.png)

Following the stack trace of the error:
```
[2020-02-28 13:28:16] api[site].ERROR: Directus\Validator\Exception\InvalidRequestException: name: This value should not be blank. in /var/www/html/site.com/admin/src/core/Directus/Services/AbstractService.php:186
Stack trace:
#0 /var/www/html/site.com/admin/src/core/Directus/Services/AbstractService.php(120): Directus\Services\AbstractService->throwErrorIfAny
directus/app#1 /var/www/html/site.com/admin/src/core/Directus/Services/AbstractService.php(398): Directus\Services\AbstractService->validate
directus/app#2 /var/www/html/site.com/admin/src/core/Directus/Services/ItemsService.php(237): Directus\Services\AbstractService->validatePayload
directus/app#3 /var/www/html/site.com/admin/src/core/Directus/Services/ItemsService.php(349): Directus\Services\ItemsService->validateManyToManyCollection
directus/app#4 /var/www/html/site.com/admin/src/endpoints/Items.php(121): Directus\Services\ItemsService->update
directus/app#5 [internal function]: Directus\Api\Routes\Items->update
directus/app#6 /var/www/html/site.com/admin/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
directus/app#7 /var/www/html/site.com/admin/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
directus/app#8 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
directus/app#9 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/app#10 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#11 [internal function]: Slim\DeferredCallable->__invoke
directus/app#12 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#13 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
directus/app#14 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
directus/app#15 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#16 [internal function]: Slim\DeferredCallable->__invoke
directus/app#17 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#18 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
directus/app#19 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
directus/app#20 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#21 [internal function]: Slim\DeferredCallable->__invoke
directus/app#22 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#23 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
directus/app#24 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
directus/app#25 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#26 [internal function]: Slim\DeferredCallable->__invoke
directus/app#27 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#28 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
directus/app#29 /var/www/html/site.com/admin/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus/app#30 /var/www/html/site.com/admin/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus/app#31 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
directus/app#32 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/app#33 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#34 [internal function]: Slim\DeferredCallable->__invoke
directus/app#35 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#36 /var/www/html/site.com/admin/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
directus/app#37 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
directus/app#38 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
directus/app#39 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#40 [internal function]: Slim\DeferredCallable->__invoke
directus/app#41 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#42 /var/www/html/site.com/admin/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
directus/app#43 [internal function]: RKA\Middleware\IpAddress->__invoke
directus/app#44 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#45 [internal function]: Slim\DeferredCallable->__invoke
directus/app#46 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#47 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
directus/app#48 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/app#49 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#50 [internal function]: Slim\DeferredCallable->__invoke
directus/app#51 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#52 /var/www/html/site.com/admin/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
directus/app#53 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
directus/app#54 /var/www/html/site.com/admin/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/app#55 [internal function]: Slim\DeferredCallable->__invoke
directus/app#56 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/app#57 /var/www/html/site.com/admin/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/app#58 /var/www/html/site.com/admin/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/app#59 /var/www/html/site.com/admin/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/app#60 /var/www/html/site.com/admin/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/app#61 /var/www/html/site.com/admin/public/index.php(5): Directus\Application\Application->run [] []
```

**Comment by rijkvanzanten** [comment]
@hemratna The API seems to return the required error for the `name` field when we only pass the `id` field. The payload from the app in this case is `{ "id": "12" }`. Seeing that the name field already has a value, the required validation shouldn't fail.

A temporary workaround would be to remove the `required` restriction from the `roles.name` field @buenyamin-olgun

**Comment by buenyamin-olgun** [comment]
> A temporary workaround would be to remove the `required` restriction from the `roles.name` field @buenyamin-olgun

Thank you, this worked well!

**Comment by hemratna** [comment]
@buenyamin-olgun I am not able to replicate this issue on https://demo.directus.io/admin/

https://www.loom.com/share/72dc74011012495cb3e9e7c95864f37a

**Comment by buenyamin-olgun** [comment]
@hemratna It was previously working on my server also. Suddenly it stopped working.

I am also unable to reproduce it on the demo server.

**Comment by hemratna** [comment]
@buenyamin-olgun Can you please confirm the same issue with other M2M relationships?

**Comment by buenyamin-olgun** [comment]
@hemratna What are the other M2M relationships?

**Comment by hemratna** [comment]
I mean try to create any other M2M relationship and verify the same behaviors.
