### ISSUE TITLE
All logins are failing with "Couldn't Reach API"

### ISSUE THREAD

**Issue by polds** [directus/api#1821]
# Bug Report

## Steps to Reproduce

(This is what I did)
1. While using directus with Docker I attempted to configure Google Auth using environment variables
2. Received errors saying the calls are using the `legacypeople api` and cannot be used (deprecated Google+)
3. Remove Google Auth environment variables
4. Now attempt to log in using normal user / pass

## Expected Behavior

After successful response, be redirected to the app.

## Actual Behavior

Receive error "Couldn't Reach API", not redirected, HTTP call appears to succeed.

## Other Context & Screenshots

I'm using Directus within Docker, it was working just fine and I tried to enable Google Authentication using envrionment variables. When that didn't appear to work (sounds like due to using the deprecated Google+ APIs?) I attempted to disable it. Now all login attempts "succeed" on the HTTP side but the App shows "Couldn't Reach API". 

![Screen Shot 2020-03-23 at 8 09 37 PM](https://user-images.githubusercontent.com/2372558/77384450-a3b46880-6d42-11ea-80e2-46fa83dc598c.png)

I don't see any relevant logs, it looks like the calls are succeeding. I've nuked the active sessions in the database, flushed redis, even blew away the Docker container, killed my own cookies and also tried from Incognito. 

After doing a login attempt and receiving the error message I can browse `_/users/me` with no issues to see the json dump of my user.

## Technical Details

- Device: Laptop
- OS: MacOS 10.15.4
- Web Server: Apache 2.4.38
- PHP Version: 7.3.15
- Database: MySQL 5.7
- Directus Release Version: 8.6.2
  - App Version: Not sure
  - API Version: Not sure
- Install Method: Docker via directus/directus:v8.6-apache

**Comment by creanovo-git** [comment]
I don't use Docker but I had a similar problem were all logins failed with "Couldn't reach API" but the return code was always 200.

I had configured a password protection for the root directory with plesk and that somehow blocked it.

You might want to check and remove all password protection and try again.

**Comment by everyx** [comment]
Directus api return `Set-Cookie` with `Secure` param, so the api login only worked for https connection.

**Comment by rijkvanzanten** [comment]
@everyx no. Browsers started updating their cookie policies and now only accept cross site cookies when using secure:

https://chromestatus.com/feature/5633521622188032

https://www.chromium.org/updates/same-site

https://digiday.com/media/what-is-chrome-samesite/

It's out of our hands really

**Comment by MrCrimp** [comment]
Same here. My stacktrace below.

`directus_1  | 172.21.0.1 - - [07/Sep/2020:06:47:45 +0000] "POST /_/auth/authenticate HTTP/1.1" 500 211 "http://localhost:7780/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.41"
directus_1  | [2020-09-07 06:47:46] api[_].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL 
query. in /var/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php:744
directus_1  | Stack trace:
directus_1  | #0 /var/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Directus\Database\TableGateway\BaseTableGateway->executeSelect
directus_1  | #1 /var/directus/src/core/Directus/Database/TableGateway/DirectusUserSessionsTableGateway.php(68): Zend\Db\TableGateway\AbstractTableGateway->selectWith
directus_1  | #2 /var/directus/src/core/Directus/Services/UserSessionService.php(75): Directus\Database\TableGateway\DirectusUserSessionsTableGateway->fetchSession
directus_1  | #3 /var/directus/src/endpoints/Auth.php(155): Directus\Services\UserSessionService->find
directus_1  | #4 /var/directus/src/endpoints/Auth.php(73): Directus\Api\Routes\Auth->storeCookieSession
directus_1  | #5 [internal function]: Directus\Api\Routes\Auth->authenticate`
