### ISSUE TITLE
Unknown column 'directus_fields' during installation

### ISSUE THREAD

**Issue by tillsanders** [directus/api#1836]
# Bug Report

## Steps to Reproduce

1. Set up a deployment using the official directus docker image.
2. Connect a MySQL 8 database.
3. Configure everything using env vars.
4. Enter the container and run `./bin/directus install:config`.
5. Run `./bin/directus install:database`
5. Get error message: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'directus_fields' in 'where clause'`

## Expected Behavior

I expected the last command to scaffold the database structure. 

## Actual Behavior

It only created `directus_field` and `directus_migrations` and threw an error: 

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'directus_fields' in 'where clause'`

## Other Context & Screenshots

I'm running the directus image inside a kubernetes cluster and connected to a MySQL 8 database with a dedicated user.

The app show this message: 

<img width="405" alt="grafik" src="https://user-images.githubusercontent.com/1533846/78062979-c0c6e800-738f-11ea-85e8-278642663081.png">

## Technical Details

- Database: MySQL 8.0.18
- Directus Image: 
  - directus/directus@sha256:f1a1ce199042d2fc7ab7ebc2dc8ab59056585592ba85df34a8d6d1716c3e09df (directus/directus:v8.6-apache)

**Comment by Alaeron** [comment]
Same issue with MySql 8 when going through the web ui install steps (DIRECTUS_APP_USE_ENV=0).
Used the docker image: directus/directus:v8.6.2-apache
I dug around in the source and logs a bit. Looks like there's an error running the install migration 20180220023156_create_fields_table.php.
Relevant error.2020-05-17.log error:
`
[2020-05-17 05:40:11] api[].ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'directus_fields' in 'where clause' in /var/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:145
Stack trace:
#0 /var/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(145): PDO->query
#1 /var/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(179): Phinx\Db\Adapter\PdoAdapter->query
#2 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(229): Phinx\Db\Adapter\AdapterWrapper->query
#3 /var/directus/migrations/install/20180220023123_create_fields_table.php(251): Phinx\Migration\AbstractMigration->query
#4 /var/directus/migrations/install/20180220023123_create_fields_table.php(241): CreateFieldsTable->checkFieldExist
#5 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(124): CreateFieldsTable->change
#6 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(375): Phinx\Migration\Manager\Environment->executeMigration
#7 /var/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration
#8 /var/directus/src/core/Directus/Util/Installation/InstallerUtils.php(235): Phinx\Migration\Manager->migrate
#9 /var/directus/src/core/Directus/Util/Installation/InstallerUtils.php(202): Directus\Util\Installation\InstallerUtils::runMigrationAndSeeder
#10 /var/directus/src/core/Directus/Services/ProjectService.php(114): Directus\Util\Installation\InstallerUtils::createTables
#11 /var/directus/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
#12 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
#13 /var/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#14 /var/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#15 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
#16 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#17 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#18 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#19 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#20 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#24 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#25 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#26 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#27 /var/directus/public/index.php(5): Directus\Application\Application->run [] []
`
which is occurring in this snippet of 20180220023156_create_fields_table.php:
`
public function checkFieldExist($collection, $field)
{
          $checkSql = sprintf('SELECT 1 FROM `directus_fields` WHERE `collection` = "%s" AND  `field` = "%s";', $collection, $field);
          return $this->query($checkSql)->fetch();
}
`
It seems to have successfully made the directus_migrations table and the directus_fields table with columns:
id
collection
field
type
interface
options
locked
validation
required
readonly
hidden_detail
hidden_browse
sort
width
group
note
translation

Any updates on this would be appreciated. Was planning to drop Directus in for a client and would prefer to not have to use something else in the intermediary.

Thanks!

**Comment by tillsanders** [comment]
I discovered a workaround. Every migration in `migrations/install` has a function like this:

```php
public function checkFieldExist($collection, $field)
{
  $checkSql = sprintf('SELECT 1 FROM `directus_fields` WHERE `collection` = "%s" AND `field` = "%s";', $collection, $field);
  return $this->query($checkSql)->fetch();
}
```

This checks, wether the tables are populated they way they should be. If this function returns true, the migration is applied. Somehow, this causes issues with MySQL 8. A simple fix is to wrap this into a try-catch block:

```php
public function checkFieldExist($collection, $field)
{
  try {
    $checkSql = sprintf('SELECT 1 FROM `directus_fields` WHERE `collection` = "%s" AND `field` = "%s";', $collection, $field);
    return $this->query($checkSql)->fetch();
  } catch (Exception $error) {
    return false;
  }
}
```

You have to do this for every migration in that folder. For some reason, this is rather unDRY code. I suspect, this will be improved, when Directus switches to Laravel (I believe, I read that somewhere). The migrations will then run successfully.

**Comment by Alaeron** [comment]
Thanks for that. That allows for the table creation to complete, unfortunately it also results in:
```
[2020-05-17 18:50:25] api[x_project_name].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (42S22 - 1054 - Unknown column 'UNI' in 'field list') in /var/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
Stack trace:
#0 /var/directus/src/core/Directus/Database/Schema/Sources/MySQLSchema.php(287): Zend\Db\Adapter\Driver\Pdo\Statement->execute
#1 /var/directus/src/core/Directus/Database/Schema/Sources/MySQLSchema.php(143): Directus\Database\Schema\Sources\MySQLSchema->getAllFields
#2 /var/directus/src/core/Directus/Database/Schema/SchemaManager.php(279): Directus\Database\Schema\Sources\MySQLSchema->getFields
#3 /var/directus/src/core/Directus/Database/Schema/SchemaManager.php(158): Directus\Database\Schema\SchemaManager->getFields
#4 /var/directus/src/core/Directus/Database/SchemaService.php(145): Directus\Database\Schema\SchemaManager->getCollection
#5 /var/directus/src/core/Directus/Application/CoreServicesProvider.php(264): Directus\Database\SchemaService::getCollection
```
when I try to log in after the install is complete. With a ui error of "Couldn't Reach API". Still investigating what's going on here, but figured I'd post an update.

**Comment by tillsanders** [comment]
I see, well unfortunately, I can't test that with my current setup. I'm using environment variables for configuration and haven't figured out how to continue the installation to get to that point :/

**Comment by sneakersgames** [comment]
Having the same errors in an existing Directus install after updating to a MySQL 8 database. Any plans to support MySQL 8?

**Comment by everyx** [comment]
> Having the same errors in an existing Directus install after updating to a MySQL 8 database. Any plans to support MySQL 8?

@sneakersgames  You can try to upgrade to PHP4.7

**Comment by rekie17** [comment]
Same issue here. Upgrading to PHP 7.4 doesn't help

**Comment by pvshum** [comment]
Hey folks I am experiencing the same issue, any update?

**Comment by lintoncaldecott** [comment]
> Thanks for that. That allows for the table creation to complete, unfortunately it also results in:
> 
> ```
> [2020-05-17 18:50:25] api[x_project_name].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (42S22 - 1054 - Unknown column 'UNI' in 'field list') in /var/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
> Stack trace:
> #0 /var/directus/src/core/Directus/Database/Schema/Sources/MySQLSchema.php(287): Zend\Db\Adapter\Driver\Pdo\Statement->execute
> #1 /var/directus/src/core/Directus/Database/Schema/Sources/MySQLSchema.php(143): Directus\Database\Schema\Sources\MySQLSchema->getAllFields
> #2 /var/directus/src/core/Directus/Database/Schema/SchemaManager.php(279): Directus\Database\Schema\Sources\MySQLSchema->getFields
> #3 /var/directus/src/core/Directus/Database/Schema/SchemaManager.php(158): Directus\Database\Schema\SchemaManager->getFields
> #4 /var/directus/src/core/Directus/Database/SchemaService.php(145): Directus\Database\Schema\SchemaManager->getCollection
> #5 /var/directus/src/core/Directus/Application/CoreServicesProvider.php(264): Directus\Database\SchemaService::getCollection
> ...
> ```
> 
> when I try to log in after the install is complete. With a ui error of "Couldn't Reach API". Still investigating what's going on here, but figured I'd post an update.

Worth piling on, I wrapped the migrations in the install folder with the try catch that was suggested and I am getting this same error now.
I am using a digital ocean directus droplet
