### ISSUE TITLE
 Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' 

### ISSUE THREAD

**Issue by cedricve** [directus/api#1911]
Hello I'm using latest version (master) of Discus, with PHP 7.3.

I noticed that following error popsup when accessing the login page.

    <br />
    <b>Fatal error</b>:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/maisonpapillon/src/core/Directus/Application/CoreServicesProvider.php:703
    Stack trace:
    #0 /var/www/maisonpapillon/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider-&gt;Directus\Application\{closure}(Object(Directus\Application\Container))
    #1 /var/www/maisonpapillon/src/core/Directus/Container/Container.php(27): Pimple\Container-&gt;offsetGet('database')
    #2 /var/www/maisonpapillon/src/core/Directus/Services/AbstractService.php(61): Directus\Container\Container-&gt;get('database')
    #3 /var/www/maisonpapillon/src/core/Directus/Services/AbstractService.php(84): Directus\Services\AbstractService-&gt;getConnection()
    #4 /var/www/maisonpapillon/src/core/Directus/Services/WebhookService.php(134): Directus\Services\AbstractService-&gt;createTableGateway('directus_webhoo...', false)
    #5 /var/www/maisonpapillon/src/core/Directus/Services/WebhookService.php(45): Directus\Services\WebhookService-&gt;getTableGateway( in <b>/var/www/maisonpapillon/src/core/Directus/Application/CoreServicesProvider.php</b> on line <b>703</b><br />

**Comment by cedricve** [comment]
looks like related to this one https://github.com/ifsnop/mysqldump-php/issues/160

**Comment by cedricve** [comment]
i didnt install pdo_mysql
