### ISSUE TITLE
Failure while creating a permissions for a role

### ISSUE THREAD

**Issue by shaunc** [directus/api#1940]
Directus: Version 8.2 (Running docker 8.2-apache)
Server: Apache, ubuntu, mysql 8.0.19
 Error:
```
127.0.0.1 - - [23/Jun/2020:04:41:20 +0000] "GET /server/ping HTTP/1.1" 200 403 "http://localhost:10401/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
[2020-06-23 04:41:25] api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionCreateException: Creating item to "directus_permissions" collection was denied in /var/directus/src/core/Directus/Permissions/Acl.php:1011
Stack trace:
#0 /var/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1090): Directus\Permissions\Acl->enforceCreate
#1 /var/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(742): Directus\Database\TableGateway\BaseTableGateway->enforceInsertPermission
#2 /var/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert
#3 /var/directus/src/core/Directus/Database/TableGateway/BaseTableGateway.php(391): Zend\Db\TableGateway\AbstractTableGateway->insert
#4 /var/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(412): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray
#5 /var/directus/src/core/Directus/Services/ItemsService.php(54): Directus\Database\TableGateway\RelationalTableGateway->createRecord
#6 /var/directus/src/core/Directus/Services/ItemsService.php(399): Directus\Services\ItemsService->createItem
#7 /var/directus/src/core/Directus/Services/PermissionsService.php(54): Directus\Services\ItemsService->batchCreate
#8 /var/directus/src/endpoints/Permissions.php(181): Directus\Services\PermissionsService->batchCreate
#9 /var/directus/src/endpoints/Permissions.php(38): Directus\Api\Routes\Permissions->batch
#10 [internal function]: Directus\Api\Routes\Permissions->create
#11 /var/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#12 /var/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#13 /var/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#14 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#15 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /var/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#19 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#20 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /var/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#24 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#25 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#26 [internal function]: Slim\DeferredCallable->__invoke
#27 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#28 /var/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#29 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#30 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#31 [internal function]: Slim\DeferredCallable->__invoke
#32 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#33 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#34 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#35 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#36 /var/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#37 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#38 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#39 [internal function]: Slim\DeferredCallable->__invoke
#40 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#41 /var/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#42 /var/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#43 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#44 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#45 [internal function]: Slim\DeferredCallable->__invoke
#46 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#47 /var/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#48 [internal function]: RKA\Middleware\IpAddress->__invoke
#49 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#50 [internal function]: Slim\DeferredCallable->__invoke
#51 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#52 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#53 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#54 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#55 [internal function]: Slim\DeferredCallable->__invoke
#56 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#57 /var/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#58 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#59 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#60 [internal function]: Slim\DeferredCallable->__invoke
#61 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#62 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#63 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#64 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#65 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#66 /var/directus/public/index.php(5): Directus\Application\Application->run [] []
```
This is when I try to save a role after setting a permission:
![image](https://user-images.githubusercontent.com/193170/85362022-71eea180-b4eb-11ea-95a2-e7aa8a21089d.png)

Without setting a permission, the role saves.

**Comment by shaunc** [comment]
Ok -- I think I know what happened. I put myself into the category. I thought that roles were inclusive (user has permissions of all roles they have). But now I am locked out.

Given this is a correct diagnosis:
* There should be an "are you sure" to prevent admin from removing themselves from admin
* Can someone please tell me how to undo this from the command line?
