### ISSUE TITLE
Failed to connect to the database

### ISSUE THREAD

**Issue by justrealmilk** [directus/api#1946]
Ubuntu 20.04, MySQL 8, PHP 7.4. Latest stuff with fresh installs

I don't think this is a bug... but I was hoping someone could help me discover the next step to working it out.

```
[2020-06-28 17:34:07] api[tc01].ERROR: Directus\Database\Exception\ConnectionFailedException: Failed to connect to the database in /www/html/src/core/Directus/Application/CoreServicesProvider.php:723
Stack trace:
#0 /www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#1 /www/html/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet
#2 /www/html/src/core/Directus/Application/CoreServicesProvider.php(1121): Directus\Container\Container->get
#3 /www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#4 /www/html/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet
#5 /www/html/src/helpers/settings.php(20): Directus\Container\Container->get
#6 /www/html/src/helpers/settings.php(35): Directus\get_directus_settings
#7 /www/html/src/helpers/settings.php(142): Directus\get_directus_setting
#8 /www/html/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(16): Directus\get_trusted_proxies
#9 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#10 /www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#11 [internal function]: Slim\DeferredCallable->__invoke
#12 /www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#13 /www/html/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#14 [internal function]: RKA\Middleware\IpAddress->__invoke
#15 /www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /www/html/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#19 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#20 /www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /www/html/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(63): Slim\App->Slim\{closure}
#24 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#25 /www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#26 [internal function]: Slim\DeferredCallable->__invoke
#27 /www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#28 /www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#29 /www/html/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#30 /www/html/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#31 /www/html/src/core/Directus/Application/Application.php(161): Slim\App->run
#32 /www/html/public/index.php(5): Directus\Application\Application->run [] []
```

When working with files and multiple tabs (requests), something somewhere seems to fall down. This looks like a generic database failure to me. Where should I look next?

**Comment by justrealmilk** [comment]
I found MySQL's error log

```
2020-06-28T17:33:49.646042Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2020-06-28T17:33:55.023479Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20) starting as process 104975
2020-06-28T17:33:55.069167Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2020-06-28T17:33:56.366734Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2020-06-28T17:33:57.043691Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
2020-06-28T17:33:57.105114Z 0 [System] [MY-010229] [Server] Starting XA crash recovery...
2020-06-28T17:33:57.136766Z 0 [System] [MY-010232] [Server] XA crash recovery finished.
2020-06-28T17:33:57.266210Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2020-06-28T17:33:57.346290Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2020-06-28T17:33:59.467800Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20) starting as process 105063
2020-06-28T17:33:59.503987Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2020-06-28T17:34:00.510517Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2020-06-28T17:34:01.229975Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
2020-06-28T17:34:01.393121Z 0 [System] [MY-010229] [Server] Starting XA crash recovery...
2020-06-28T17:34:01.458368Z 0 [System] [MY-010232] [Server] XA crash recovery finished.
2020-06-28T17:34:01.681555Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2020-06-28T17:34:01.817160Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2020-06-28T17:34:04.516672Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20) starting as process 105155
2020-06-28T17:34:04.591383Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2020-06-28T17:34:05.895055Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2020-06-28T17:34:07.327492Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
2020-06-28T17:34:07.445017Z 0 [System] [MY-010229] [Server] Starting XA crash recovery...
2020-06-28T17:34:07.520276Z 0 [System] [MY-010232] [Server] XA crash recovery finished.
2020-06-28T17:34:07.713840Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2020-06-28T17:34:07.773338Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2020-06-28T17:46:14.629742Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20) starting as process 105693
2020-06-28T17:46:14.665028Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2020-06-28T17:46:15.722527Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2020-06-28T17:46:16.071202Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
2020-06-28T17:46:16.107386Z 0 [System] [MY-010229] [Server] Starting XA crash recovery...
2020-06-28T17:46:16.124625Z 0 [System] [MY-010232] [Server] XA crash recovery finished.
2020-06-28T17:46:16.202510Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2020-06-28T17:46:16.247440Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
```

Looks like it's crashing... but... why

**Comment by justrealmilk** [comment]
It's crashing my because my server is running out of memory. Case closed. Thank you all for attending.
