### ISSUE TITLE
Posting files in multipart/form-data doesn't work

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#210]
When sending a JPEG image:

```
<br />
<b>Fatal error</b>:  Uncaught RuntimeException: Malformed UTF-8 characters, possibly incorrectly encoded in /Users/rijkvanzanten/Development/api/vendor/slim/slim/Slim/Http/Response.php:353
Stack trace:
#0 /Users/rijkvanzanten/Development/api/src/core/Directus/Application/ErrorHandlers/ErrorHandler.php(82): Slim\Http\Response-&gt;withJson(Array)
#1 [internal function]: Directus\Application\ErrorHandlers\ErrorHandler-&gt;__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Exception\ForbiddenException))
#2 /Users/rijkvanzanten/Development/api/vendor/slim/slim/Slim/App.php(683): call_user_func_array(Object(Directus\Application\ErrorHandlers\ErrorHandler), Array)
#3 /Users/rijkvanzanten/Development/api/vendor/slim/slim/Slim/App.php(408): Slim\App-&gt;handleException(Object(Directus\Exception\ForbiddenException), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#4 /Users/rijkvanzanten/Development/api/vendor/slim/slim/Slim/App.php(314): Slim\App-&gt;pr in
<b>/Users/rijkvanzanten/Development/api/vendor/slim/slim/Slim/Http/Response.php</b> on line
<b>353</b>
<br />
```

**Comment by WellingGuzman** [comment]
Can you set the environment to `production`? It's probably a separate issue that cannot be rendered because the stack trace has the data information and `json_encode` could not encode it.
