### ISSUE TITLE
Error while trying to edit a text input field in a collection's settings - SQLSTATE[42000]: Syntax error or access violation: 1064 

### ISSUE THREAD

**Issue by AlexisWalravens** [directus/api#758]
# Bug Report
Following error while attempting to edit a Text Input field on a collection's settings:
```
PATCH http://mysuperapi.dev/_/fields/products/name 500 (Internal Server Error)
class: "PDOException"
code: null
file: "D:\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Connection.php"
line: 379
message: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2"
```

EDIT:
I think it has to do with the default value, if I enter something in the default value and try to save the field I get this error: 
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near  'DEFAULT 'something'' at line 2`

## Steps to Reproduce

Not sure how exactly this happens but:
It happened multiple times as the first time I got the error I deleted the field and recreated it, I don't remember having this error on the field creation, only editing it.

So...
1. Create a text input field on a collection
2. Try to edit the newly created field by clicking on it and just hit the 'save' button
3. Nothing happens, the modal stays open, and if you go to the inspector you see the error.

## Expected Behavior
Save the edited field.

## Actual Behavior
Nothing happens, the modal stays open, and if you go to the inspector you see the error.

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/1764824/52269465-7211ef80-293e-11e9-9b9f-7c50a6458a8c.png)

## Technical Details
- OS: MacOS 10.13.6
- Browser: Chrome 71
- Directus App: v7.0.16
- Directus API: v2.0.16
- Install Method: git clone https://github.com/directus/directus.git
- MySQL: 5.7.21
- PHP: 7.2.14
- Apache: 2.3.37

Edit - Here's the stack trace: 
```
[2019-02-05 15:22:19] api[mysuperapi].ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 Erreur de syntaxe près de '' à la ligne 2 in D:\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Connection.php:379
Stack trace:
#0 D:\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Connection.php(379): PDO->query
#1 D:\directus\vendor\zendframework\zend-db\src\Adapter\Adapter.php(205): Zend\Db\Adapter\Driver\Pdo\Connection->execute
#2 D:\directus\src\core\Directus\Database\Schema\SchemaFactory.php(240): Zend\Db\Adapter\Adapter->query
#3 D:\directus\src\core\Directus\Services\TablesService.php(1244): Directus\Database\Schema\SchemaFactory->buildTable
#4 D:\directus\src\core\Directus\Services\TablesService.php(604): Directus\Services\TablesService->updateTableSchema
#5 D:\directus\src\endpoints\Fields.php(110): Directus\Services\TablesService->changeColumn
#6 [internal function]: Directus\Api\Routes\Fields->update
#7 D:\directus\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func
#8 D:\directus\vendor\slim\slim\Slim\Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#9 D:\directus\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#10 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#11 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#14 D:\directus\src\core\Directus\Application\Http\Middleware\AuthenticationMiddleware.php(80): Slim\Route->Slim\{closure}
#15 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#16 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#19 D:\directus\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#21 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#24 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#25 D:\directus\vendor\slim\slim\Slim\Route.php(334): Slim\Route->callMiddlewareStack
#26 D:\directus\vendor\slim\slim\Slim\App.php(516): Slim\Route->run
#27 D:\directus\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#28 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#29 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#32 D:\directus\vendor\wellingguzman\proxy-detection\src\ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#33 D:\directus\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#34 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#35 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#36 [internal function]: Slim\DeferredCallable->__invoke
#37 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#38 D:\directus\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#39 [internal function]: RKA\Middleware\IpAddress->__invoke
#40 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#41 [internal function]: Slim\DeferredCallable->__invoke
#42 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#43 D:\directus\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(66): Slim\App->Slim\{closure}
#44 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#45 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#46 [internal function]: Slim\DeferredCallable->__invoke
#47 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#48 D:\directus\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#49 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#50 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#51 [internal function]: Slim\DeferredCallable->__invoke
#52 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#53 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#54 D:\directus\vendor\slim\slim\Slim\App.php(407): Slim\App->callMiddlewareStack
#55 D:\directus\vendor\slim\slim\Slim\App.php(315): Slim\App->process
#56 D:\directus\src\core\Directus\Application\Application.php(161): Slim\App->run
#57 D:\directus\public\index.php(5): Directus\Application\Application->run [] []
```

**Comment by WellingGuzman** [comment]
This bug was already fixed in 7.0.17 (API: 2.0.17). Reference: https://github.com/directus/api/issues/741

**Comment by WellingGuzman** [comment]
@AlexisWalravens please upgrade to the latest version. This bug should've been resolved, otherwise please let us know.

**Comment by AlexisWalravens** [comment]
Just upgraded to 7.0.17. It works.
Before posting this bug, I was about to update to 7.0.17 but by the time I wanted to do it the release was pulled out, so I couldn't try it.

Anyways, glad it's fixed. Thanks.
