### ISSUE TITLE
[v2.0.17] Reading items of collection was denied but I allowed it

### ISSUE THREAD

**Issue by gnh1201** [directus/api#769]
There is a problem in some collections that ACLs do not work.
I checked to allow reading, but I was denied. What should I do to debug this problem?

```
 ====== 'something' role's ACL ======
                             read      write
 Collection A        [ V ]        [    ]
 Collection B        [ V ]        [    ]
 ===============================
```

try 1) `GET /_/items/collection_a` -> reading works well.
try 2) `GET /_/items/collection_b` -> reading denied.

```
[2019-02-13 12:58:41] api[_].ERROR: Directus\Permissions\Exception\ForbiddenCollectionReadException: Reading items from "catswords_tab" collection was denied in /utilhome/api/src/core/Directus/Permissions/Acl.php:988
Stack trace:
#0 /utilhome/api/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1142): Directus\Permissions\Acl->enforceReadOnce
#1 /utilhome/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1017): Directus\Database\TableGateway\BaseTableGateway->enforceReadPermission
#2 /utilhome/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1131): Directus\Database\TableGateway\RelationalTableGateway->fetchItems
#3 /utilhome/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(819): Directus\Database\TableGateway\RelationalTableGateway->fetchData
#4 [internal function]: Directus\Database\TableGateway\RelationalTableGateway->getItems
#5 /utilhome/api/src/core/Directus/Services/AbstractService.php(332): call_user_func_array
#6 /utilhome/api/src/core/Directus/Services/AbstractService.php(276): Directus\Services\AbstractService->getDataAndSetResponseCacheTags
#7 /utilhome/api/src/core/Directus/Services/ItemsService.php(56): Directus\Services\AbstractService->getItemsAndSetResponseCacheTags
#8 /utilhome/api/src/endpoints/Items.php(43): Directus\Services\ItemsService->findAll
#9 [internal function]: Directus\Api\Routes\Items->all
#10 /utilhome/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#11 /utilhome/api/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#12 /utilhome/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#13 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#14 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#15 [internal function]: Slim\DeferredCallable->__invoke
#16 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#17 /utilhome/api/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#18 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#19 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#20 [internal function]: Slim\DeferredCallable->__invoke
#21 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#22 /utilhome/api/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#23 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#24 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#25 [internal function]: Slim\DeferredCallable->__invoke
#26 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#27 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#28 /utilhome/api/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#29 /utilhome/api/vendor/slim/slim/Slim/App.php(516): Slim\Route->run
#30 /utilhome/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#31 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#32 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#33 [internal function]: Slim\DeferredCallable->__invoke
#34 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#35 /utilhome/api/vendor/wellingguzman/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#36 /utilhome/api/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#37 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#38 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#39 [internal function]: Slim\DeferredCallable->__invoke
#40 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#41 /utilhome/api/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#42 [internal function]: RKA\Middleware\IpAddress->__invoke
#43 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#44 [internal function]: Slim\DeferredCallable->__invoke
#45 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#46 /utilhome/api/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#47 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#48 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#49 [internal function]: Slim\DeferredCallable->__invoke
#50 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#51 /utilhome/api/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#52 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#53 /utilhome/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#54 [internal function]: Slim\DeferredCallable->__invoke
#55 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#56 /utilhome/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#57 /utilhome/api/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack
#58 /utilhome/api/vendor/slim/slim/Slim/App.php(315): Slim\App->process
#59 /utilhome/api/src/core/Directus/Application/Application.php(161): Slim\App->run
#60 /utilhome/api/public/index.php(5): Directus\Application\Application->run [] []

```

**Comment by WellingGuzman** [comment]
@gnh1201 can you share a database schema (sql database dump) that we can use to reproduce this issue?

What differences have these collections? Does one of them have status field?

**Comment by gnh1201** [comment]
This problem has been fixed by adding the status field to collection.
But I wonder why ACLs only work with the status field.

**Comment by benhaynes** [comment]
You should only _need_ a status field if you want to use the "workflow" permissions.

@WellingGuzman any idea what's up here?

**Comment by WellingGuzman** [comment]
That's correct @gnh1201, you only need the status field if you want to use the workflow. Unless the permission was created for workflow without having a status field.

If adding the status field fixed it, it meant the workflow permission was created for a collection without status field.

**Comment by rijkvanzanten** [comment]
This seems to be working as expected on our live demo (on 2.0.17 as well).

@gnh1201 could you share a database dump so we can reproduce your exact setup?

**Comment by gnh1201** [comment]
This issue has been fixed by adding a status field. I will soon close this issue.
But, I can send a dump to fix another issue.
If you need it, where can I send it?

**Comment by benhaynes** [comment]
Our community Slack is best — you can DM it directly to Rijk:

https://slack.directus.io/
