### ISSUE TITLE
Fail to send mail

### ISSUE THREAD

**Issue by Calderis** [directus/api#867]
# Bug Report

It seems that sending mail through sendmail fail due to some reasons (error code null)

## Steps to Reproduce

1. Make a POST request to `/_/mail`
2. set body to 
```
{
  "to": "r.wetteren@gmail.com",
  "subject": "New Password",
  "body": "Hello",
  "type": "html"
}
```

## Expected Behavior

Should receive code 220 and send mail

## Actual Behavior

No mail sent and response returned by server :
```
{
    "error": {
        "code": null,
        "message": "Expected response code 220 but got code \"\", with message \"\""
    }
}
```

**Logs**
----
```
[2019-04-01 12:46:21] api[_].ERROR: Swift_TransportException: Expected response code 220 but got code "", with message "" in /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes
Stack trace:
#0 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_assertResponseCode
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(51): Swift_Transport_AbstractSmtpTransport->start
#3 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_SendmailTransport->start
#4 /var/www/html/src/core/Directus/Mail/Mailer.php(76): Swift_Mailer->send
#5 /var/www/html/src/helpers/mail.php(62): Directus\Mail\Mailer->sendWithContent
#6 /var/www/html/src/helpers/mail.php(44): Directus\send_mail_with_content
#7 /var/www/html/src/core/Directus/Services/MailService.php(39): Directus\send_mail_with_layout
#8 /var/www/html/src/endpoints/Mail.php(22): Directus\Services\MailService->send
#9 [internal function]: Directus\Api\Routes\Mail->send
#10 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#11 /var/www/html/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#12 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#13 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#14 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#15 [internal function]: Slim\DeferredCallable->__invoke
#16 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#17 /var/www/html/src/core/Directus/Application/Http/Middleware/AuthenticatedMiddleware.php(18): Slim\Route->Slim\{closure}
#18 [internal function]: Directus\Application\Http\Middleware\AuthenticatedMiddleware->__invoke
#19 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#20 [internal function]: Slim\DeferredCallable->__invoke
#21 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#22 /var/www/html/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#23 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#24 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#25 [internal function]: Slim\DeferredCallable->__invoke
#26 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#27 /var/www/html/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#28 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#29 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#33 /var/www/html/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#34 /var/www/html/vendor/slim/slim/Slim/App.php(516): Slim\Route->run
#35 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#36 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#37 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#38 [internal function]: Slim\DeferredCallable->__invoke
#39 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#40 /var/www/html/vendor/wellingguzman/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#41 /var/www/html/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#42 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#43 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#44 [internal function]: Slim\DeferredCallable->__invoke
#45 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#46 /var/www/html/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#47 [internal function]: RKA\Middleware\IpAddress->__invoke
#48 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#49 [internal function]: Slim\DeferredCallable->__invoke
#50 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#51 /var/www/html/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#52 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#53 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#54 [internal function]: Slim\DeferredCallable->__invoke
#55 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#56 /var/www/html/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#57 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#58 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#59 [internal function]: Slim\DeferredCallable->__invoke
#60 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#61 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#62 /var/www/html/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack
#63 /var/www/html/vendor/slim/slim/Slim/App.php(315): Slim\App->process
#64 /var/www/html/src/core/Directus/Application/Application.php(161): Slim\App->run
#65 /var/www/html/public/index.php(5): Directus\Application\Application->run [] []
```
----

## Other Context & Screenshots

Configuration : Docker
env:
```
MAIL_DEFAULT_FROM=r.wetteren@gmail.com
MAIL_DEFAULT_TRANSPORT=sendmail
```

I try localhost and vps, no differences :/

I also try the `_/auth/password/request` but I do not receive anything in my box.

## Technical Details

- Device: Desktop
- OS: Debian Jessie
- Web Server: x
- PHP Version: 7.2.13
- Database: MySQL 5.7.25
- Install Method: Docker

**Comment by Calderis** [comment]
Hi again,

I've been trying again this morning and I also have this response back from the api. It's quite random ~~ 🤭.
```
{
    "error": {
        "code": null,
        "message": "Process could not be started [/usr/sbin/sendmail: unrecognized option: b\n]"
    }
}
```

**Comment by bjgajjar** [comment]
@Calderis 

May I know your configuration? Did you register `from` and `transport` only or `sendmail` too?

If you go through the docs, you can find that you can override the default `sendmail` option.

> The location of the sendmail command. This value is only required if the path is not /usr/sbin/sendmail

**Comment by Calderis** [comment]
Hi @bjgajjar ,

Actually my config [is still the default one](https://docs.directus.io/advanced/api/configuration.html#mail) (`/config/api.php`):
```
'mail' => [
    'default' => [
        'transport' => getenvs('MAIL_DEFAULT_TRANSPORT', 'sendmail'),
        'from' => getenvs('MAIL_DEFAULT_FROM', 'admin@example.com')
    ],
],
```

So in fact only `transport` and `from` are specified. I did not update the `sendmail` value since the `sendmail` program is at the default path [such as specified in the documentation](https://docs.directus.io/advanced/api/configuration.html#sendmail) (`/usr/sbin/sendmail`)

**Comment by Calderis** [comment]
@bjgajjar 
Does someone already managed to send mail through the `sendmail` transport with Directus on Docker alpine ?

**Comment by benhaynes** [comment]
Hmm, @wolfulus — any idea?

**Comment by WoLfulus** [comment]
I was reading sendmail docs and how to get it working, and unfortunately I don't think the current images will work without modifications. It needs some local file modifications and an agent running.

You can add support for those by extending the image... I'll try adding those on the docker refactor branch

**Comment by Calderis** [comment]
I did another try with the `smtp` transport.

I've been filling config such as:
```
'mail' => [
    'default' => [
        'transport' => 'smtp',
        'from' => 'auto@mydomain.com',
        'host' => 'smtp.mydomain.com',
        'port' => 465,
        'username' => 'team@mydomain.com',
        'password' => 'mypassword',
        'encryption' => 'ssl'
    ],
]
```

and this time I've been receiving the following error :
```
{
    "error": {
        "code": null,
        "message": "Connection could not be established with host smtp.coraye.com [ #0]"
    }
}
```

I thought that it might be relative to a [post on stackoverflow](https://stackoverflow.com/questions/27721120/laravel-connection-could-not-be-established-with-host-smtp-gmail-com-0). Unfortunately I don't know what to do on my side since.

Beside, I'm not sure that this is Docker related. Would it be ?

**Comment by WoLfulus** [comment]
I was going to suggest that. You can always fine tune your settings by mounting your own `api.php` file. 

If you're not going to use sendmail then you should be good at the docker side and its a matter of getting the right settings.

Also, can you try `tls` instead?

**Comment by Calderis** [comment]
`tls` doesn't work either. I do receive :
```
{
    "error": {
        "code": null,
        "message": "Connection could not be established with host smtp.coraye.com [Operation timed out #110]"
    }
}
```

Even trying updating `/etc/hosts` by adding the ip with the smtp.mydomain.com.

**Comment by WoLfulus** [comment]
The docker container has external network access? It seems connectivity issues

**Comment by Calderis** [comment]
@WoLfulus I though you were right but `ping smtp.xxxx.com` does work successfully.
My docker-compose is the following one :
```
version: "3"

services:

  #
  # Database
  #
  database:
    container_name: directus_db
    image: mysql:5.7
    env_file: ./.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 6033:3306

  #
  # PhpMyAdmin
  #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8080:80
  #
  # API
  #
  api:
    container_name: directus_api
    build: .
    env_file: ./.env
    ports:
      - 7000:80

  #
  # Dashboard
  #
  app:
    container_name: directus_app
    image: directus/app:latest
    env_file: ./.env
    ports:
      - 8000:80
```

And the Dockerfile from api container
```
FROM directus/api:latest

COPY ./public /var/www/html/public
COPY ./config/api.php /var/www/html/config/api.php

ENTRYPOINT ["/init"]
```

Nothing really unusual about mapping so.

**Comment by Calderis** [comment]
### Solution
I did succeed following this issue comment https://github.com/swiftmailer/swiftmailer/issues/544#issuecomment-220103233

Indeed I've been modifying the `src/core/Directus/Mail/Transports/SmtpTransport.php` file such as

```
<?php

namespace Directus\Mail\Transports;

class SmtpTransport extends AbstractTransport
{
    /**
     * @var \Swift_SmtpTransport
     */
    protected $smtp;

    /**
     * @return \Swift_SmtpTransport
     */
    public function getSwiftTransport()
    {
        if (!$this->smtp) {
            $transport = \Swift_SmtpTransport::newInstance(
                $this->config->get('host', 'localhost'),
                $this->config->get('port', 25)
            );

            if ($this->config->has('username')) {
                $transport->setUsername($this->config->get('username'));
            }

            if ($this->config->has('password')) {
                $transport->setPassword($this->config->get('password'));
            }

            if ($this->config->has('encryption')) {
                $transport->setEncryption($this->config->get('encryption'));
            }

            if ($this->config->has('verify_peer')) {
              $https['ssl']['verify_peer'] = FALSE;
              $https['ssl']['verify_peer_name'] = FALSE;

              $transport->setStreamOptions($https);
            }

            $this->smtp = $transport;
        }

        return $this->smtp;
    }
}

```
> the ` if ($this->config->has('verify_peer'))` has been added
> In my `api.php` I've added the `'verify_peer' => FALSE` value.

For those who would have a similar problem to send mail through **smtp/ssl** with **Docker** here my complete api.php values (just `mail` has been modifying)

```
'mail' => [
    'default' => [
        'transport' => 'smtp',
        'from' => 'team@xxxx.com',
        'host' => 'smtp.xxxx.com',
        'port' => '465',
        'username' => 'team@xxxx.com',
        'password' => 'xxxxxxx',
        'encryption' => 'ssl',
        'verify_peer' => FALSE
    ],
],
```

------
Hi, @WoLfulus & @bjgajjar 
I think it would be nice for others to simply add the **verify_peer** condition within the `api.php` without having to update the **SmtpTransport** file. How should I proceed ?

Also, I would like to share my full docker implementation to help ones who would like to setup Directus through Docker. Again, how should I proceed ?

**Comment by bjgajjar** [comment]
Hey @Calderis,

I checked this for the `API` with Gmail and Mailtrap. I am able to get the mail without using **verify_peer**. 

Just for the clarification;
If you use the Google as domain then you need to generate the `App Password` from Google security. 

You will not get this issue after the latest version of Docker will be released.
