### ISSUE TITLE
Item fails to be saved in collection with JSON field type

### ISSUE THREAD

**Issue by agseco** [directus/api#880]
# Bug Report

## Steps to Reproduce

1. Create a new collection
2. Add a text field type
3. Add a JSON field type (code)
4. Save the collection
5. Navigate to the created collection
6. Add a new item
7. Populate the text field with some text
8. Populate the JSON field with a valid JSON
9. Try to save the changes
10. It fails in the UI with the error `Attempting to write an array as the value for field "translations" in "json_test"`

## Expected Behavior

It should save the new item.

## Actual Behavior

It fails.

## Other Context & Screenshots

The error stack trace in the API:

```
[2019-04-10 08:56:55] api[pip].ERROR: Directus\Database\Exception\SuppliedArrayAsColumnValue: Attempting to write an array as the value for field "translations" in "test" in /var/www/localhost/web/src/core/Directus/Database/TableGateway/BaseTableGateway.php:1762
Stack trace:
#0 /var/www/localhost/web/src/core/Directus/Database/TableGateway/BaseTableGateway.php(372): Directus\Database\TableGateway\BaseTableGateway->validateRecordArray
#1 /var/www/localhost/web/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(410): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray
#2 /var/www/localhost/web/src/core/Directus/Services/ItemsService.php(29): Directus\Database\TableGateway\RelationalTableGateway->createRecord
#3 /var/www/localhost/web/src/endpoints/Items.php(69): Directus\Services\ItemsService->createItem
#4 [internal function]: Directus\Api\Routes\Items->create
#5 /var/www/localhost/web/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#6 /var/www/localhost/web/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#7 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#8 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#9 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#10 [internal function]: Slim\DeferredCallable->__invoke
#11 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#12 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#13 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#14 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#15 [internal function]: Slim\DeferredCallable->__invoke
#16 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#17 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#18 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#19 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#20 [internal function]: Slim\DeferredCallable->__invoke
#21 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#22 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#23 /var/www/localhost/web/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#24 /var/www/localhost/web/vendor/slim/slim/Slim/App.php(516): Slim\Route->run
#25 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#26 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#27 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#28 [internal function]: Slim\DeferredCallable->__invoke
#29 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#30 /var/www/localhost/web/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#31 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#32 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#33 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#34 [internal function]: Slim\DeferredCallable->__invoke
#35 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#36 /var/www/localhost/web/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#37 [internal function]: RKA\Middleware\IpAddress->__invoke
#38 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#39 [internal function]: Slim\DeferredCallable->__invoke
#40 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#41 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#42 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#43 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#44 [internal function]: Slim\DeferredCallable->__invoke
#45 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#46 /var/www/localhost/web/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#47 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#48 /var/www/localhost/web/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#49 [internal function]: Slim\DeferredCallable->__invoke
#50 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#51 /var/www/localhost/web/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#52 /var/www/localhost/web/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack
#53 /var/www/localhost/web/vendor/slim/slim/Slim/App.php(315): Slim\App->process
#54 /var/www/localhost/web/src/core/Directus/Application/Application.php(161): Slim\App->run
#55 /var/www/localhost/web/public/index.php(5): Directus\Application\Application->run [] []
```

## Technical Details

Directus Suite 190352A.

- Device: Any
- OS: MacOS 10.13.6 (dev) or Amazon Linux AMI 2018.03 (prod)
- Web Server: nginx/1.14.1
- PHP Version: 7.3.2
- Database: MySQL 5.7.25
- Install Method: Docker (dev), cloned `master` branch (prod)

**Comment by justrealmilk** [comment]
it creates the field with type `String` instead of `JSON`
if you go back and change it after the fact, it works
![image](https://user-images.githubusercontent.com/156681/55936586-13d4f600-5c7a-11e9-9712-3a257eb92d10.png)
so is this an API error or App error? someone should check the save request for initially adding the field

**Comment by agseco** [comment]
@justrealmilk you are totally right, it works fine if `JSON` field type is selected, thank you very much :)

**Comment by rijkvanzanten** [comment]
Good point. I can set it to JSON field type by default, but then it will break if you try saving a non-JSON value, like a string of regular code 🤔
